# Generated by Django 6.0.7 on 2026-08-07 12:18

import django.utils.timezone
import skill_global.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('skill_global', '0009_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='liveclass',
            options={'ordering': ['display_order', 'scheduled_at'], 'verbose_name': 'Live Class', 'verbose_name_plural': 'Live Classes'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', skill_global.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='banner_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='category',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Data Science', 'Data Science'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Digital Marketing', 'Digital Marketing'), ('Leadership', 'Leadership'), ('UI/UX Design', 'UI/UX Design')], max_length=120),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='certificate_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='class_type',
            field=models.CharField(blank=True, choices=[('Live Session', 'Live Session'), ('Webinar', 'Webinar'), ('Workshop', 'Workshop'), ('Masterclass', 'Masterclass')], max_length=50),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='enrolled_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='language',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='learning_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='max_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='meeting_platform',
            field=models.CharField(blank=True, choices=[('Google Meet', 'Google Meet'), ('Zoom', 'Zoom'), ('Microsoft Teams', 'Microsoft Teams')], max_length=50),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recording_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Live Now', 'Live Now'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=50),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='liveclasses/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
