# Generated by Django 6.0.5 on 2026-08-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_global', '0013_courseenrollment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
